### ISSUE TITLE
[bug] intl conflict

### ISSUE THREAD

**Issue by yichaosun** [rwbr/flutter_neat_and_clean_calendar#60]
Because flutter_neat_and_clean_calendar >=0.3.14-dev.1 depends on intl ^0.18.1 and every version of flutter_localizations from sdk depends on intl 0.18.0, flutter_neat_and_clean_calendar >=0.3.14-dev.1 is incompatible with flutter_localizations from sdk

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

flutter_neat_and_clean_calendar: ^0.3.14+32
```
